Repository farna-commits/Embedded_Systems_Project, pull requests merged in 2021-04, with the labels that each got.

#1 JSON database and Keypad
  database.xls
  database_json.h
  excel_to_json.py
  keypad_new.c
  keypad_new.h
  main/main.ino
Labels: good first issue

#4 Keypad + Diffie Hellman + AES. Still needs integration with keypad, UART connection
  database.xls
  excel_to_json.py
  main/main.ino
  methods.c
  methods.h
Labels: enhancement

#6 - fixed small issue of declaring variable early that caused wrong decryption
  main/main.ino
Labels: bug

#7 Hashing function into a string not 8 longs
  excel_to_json.py
  hashing.c
  main/main.ino
  methods.c
  methods.h
  test_hash.c
Labels: enhancement

#8 Working hashing funciton tested in main
  hashing.c
  main/main.ino
  test_hash.c
Labels: enhancement

#9 Added function that sends packet using tinyproto with custom first byte header
  listener.ino
  main/main.ino
  methods.c
  methods.h
  sender.ino
Labels: enhancement

#10 -wrapped receiver funtion receive_packet() (needs testing)
  methods.c
  methods.h
Labels: enhancement

#11 Testing of sending and receiving packet on arduino
  listener.ino
  main/main.ino
  methods.c
  methods.h
  sender.ino
Labels: enhancement

#12 Rx side (Database) enhancements
  comm_master.c
  comm_slave.c
  main/main.ino
  main_database/main_database.ino
  methods.c
  methods.h
Labels: documentation, enhancement

#13 - send and receive more than once
  methods.c
Labels: enhancement

#14 - some cleaning
  methods.c
  methods.h
Labels: documentation

#15 Tested diffie hellman, needs integration
  diife/diife.ino
  methods.c
Labels: enhancement

#16 Abl el 7adsa
  comm_master.c
  comm_slave.c
  listener.ino
  main/main.ino
  main_database/main_database.ino
  methods.c
  methods.h
  sender.ino
Labels: bug, invalid

#17 Tested encryption and decryption without keypad and hashing
  diife/diife.ino
  main/main.ino
  main_database/main_database.ino
  methods.c
  methods.h
  methods_new.c
Labels: enhancement

#18 - Integrated hashing in database function, some code cleaning
  hashing.c
  main/main.ino
  main_database/main_database.ino
  methods.h
  methods_new.c
Labels: documentation, enhancement

#19 Added a function to check ID w/ DB (Needs C-check)
  methods.h
  methods_new.c
Labels: Needs Testing
